server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ushan-Gimhan/sarasavi-configurations.git
          default-label: main
          clone-on-start: true
          timeout: 10
          force-pull: true

        native:
          search-locations: classpath:/config-repo

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.config: INFO